[package]
name = "h8pks_rs"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.29.1", features = [
    "default",
    "__screenshot", # __screenshot is so we can dump a screenshot using EFRAME_SCREENSHOT_TO
] }
log = { version = "0.4.22" }
env_logger = { version = "0.11", default-features = false, features = [
    "auto-color",
    "humantime",
] }
tokio = { version = "1.42", features = ["full"] }
tokio-util = { version = "0.7.13", features = ["full"] }
tokio-stream = { version = "0.1.17" }
rfd = { version = "0.15" }
